# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
title: Junteng Liu
email: jliugi@connect.ust.hk
description: >-
  Junteng Liu is a first-year PhD candidate at the HKUST NLP Group, Hong Kong
  University of Science and Technology. His research focuses on natural
  language processing and machine learning.

twitter_username: junteng88716710
github_username: Vicent0205

url: "https://maerjerse.github.io" # the base hostname & protocol for your site
baseurl: "/LJT-Homepage" # the subpath of your site
repository: "maerjerse/LJT-Homepage" # GitHub username/repo-name

# Site Author
# The author block is used in the sidebar of the home page and in meta tags.
author:
  name: Junteng Liu
  email: jliugi@connect.ust.hk
  github: Vicent0205
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  twitter: junteng88716710

# Collections
collections:
  publications:
    output: true
  talks:
    output: true
  teaching:
    output: true
  portfolio:
    output: true

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      share: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: /page:num/
permalink: /:year/:month/:day/:title/
excerpt_separator: "\n\n"

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
